apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busy
  name: busy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busy
  template:
    metadata:
      labels:
        app: busy
    spec:
      containers:
      - image: busybox:1.28
        name: busybox
        command:
          - tail
          - -f 
          - /dev/null
        env:
          - name: STAGE
            value: Kubernetes
          - name: PodName
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: HostIP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: TEACHER
            valueFrom:
              configMapKeyRef:
                name: busy
                key: Formateur
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: busy
                key: Password
        envFrom:
          - configMapRef:
              name: busy
