apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: pod-list-stage
  namespace: labo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-list
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: stage
